// build_lesson_meta.js
// Generates accurate, controlled multilingual metadata (title & summary) for all 209 curriculum lessons
// Across all 10 supported languages (en, hi, ta, te, kn, ml, bn, mr, gu, pa).

const fs = require('fs');
const path = require('path');

const lessons = JSON.parse(fs.readFileSync('C:/Users/lenovo/.gemini/antigravity-ide/brain/65448d18-9796-4090-bc4f-8095fa1bc059/scratch/all_lessons.json', 'utf8'));

// Dictionaries for localized terms & concepts
const TERMS = {
  hi: {
    'Quantum': 'क्वांटम',
    'Computing': 'कंप्यूटिंग',
    'Algorithm': 'एल्गोरिदम',
    'Algorithms': 'एल्गोरिदम',
    'Gate': 'गेट',
    'Gates': 'गेट्स',
    'Qubit': 'क्यूबिट',
    'Qubits': 'क्यूबिट्स',
    'Superposition': 'सुपरपोज़िशन',
    'Entanglement': 'एंटैंगलमेंट',
    'Measurement': 'मापन',
    'Vector': 'सदिश',
    'Vectors': 'सदिश',
    'Matrix': 'आव्यूह',
    'Matrices': 'आव्यूह',
    'Linear Algebra': 'रैखिक बीजगणित',
    'Complex Numbers': 'सम्मिश्र संख्याएं',
    'Error Correction': 'त्रुटि सुधार',
    'Simulation': 'सिमुलेशन',
    'Physics': 'भौतिकी',
    'Hardware': 'हार्डवेयर',
    'Mechanics': 'यांत्रिकी',
    'Phase': 'कला',
    'States': 'अवस्थाएं',
    'State': 'अवस्था',
    'Transform': 'रूपांतरण',
    'Fourier': 'फूरियर',
    'Circuits': 'परिपथ',
    'Circuit': 'परिपथ',
    'Introduction': 'परिचय',
    'Foundations': 'आधारभूत सिद्धांत',
    'Overview': 'अवलोकन',
    'Summary': 'सारांश'
  },
  ta: {
    'Quantum': 'குவாண்டம்',
    'Computing': 'கணினி',
    'Algorithm': 'அல்காரிதம்',
    'Algorithms': 'அல்காரிதங்கள்',
    'Gate': 'வாயில்',
    'Gates': 'வாயில்கள்',
    'Qubit': 'குயூபிட்',
    'Qubits': 'குயூபிட்கள்',
    'Superposition': 'சூப்பர்போசிஷன்',
    'Entanglement': 'பின்னல்',
    'Measurement': 'அளவீடு',
    'Vector': 'திசையன்',
    'Vectors': 'திசையன்கள்',
    'Matrix': 'அணி',
    'Matrices': 'அணிகள்',
    'Linear Algebra': 'நேரியல் இயற்கணிதம்',
    'Complex Numbers': 'சிக்கலெண்கள்',
    'Error Correction': 'பிழை திருத்தம்',
    'Simulation': 'உருவகப்படுத்துதல்',
    'Physics': 'இயற்பியல்',
    'Hardware': 'வன்பொருள்',
    'Mechanics': 'இயக்கவியல்',
    'Phase': 'கட்டம்',
    'States': 'நிலைகள்',
    'State': 'நிலை',
    'Transform': 'உருமாற்றம்',
    'Fourier': 'ஃபூரியர்',
    'Circuits': 'சுற்றுகள்',
    'Circuit': 'சுற்று',
    'Introduction': 'அறிமுகம்',
    'Foundations': 'அடித்தளம்',
    'Overview': 'கண்ணோட்டம்',
    'Summary': 'சுருக்கம்'
  },
  te: {
    'Quantum': 'క్వాంటం',
    'Computing': 'కంప్యూటింగ్',
    'Algorithm': 'అల్గోరిథం',
    'Algorithms': 'అల్గోరిథంలు',
    'Gate': 'గేట్',
    'Gates': 'గేట్లు',
    'Qubit': 'క్యుబిట్',
    'Qubits': 'క్యుబిట్లు',
    'Superposition': 'సూపర్‌పొజిషన్',
    'Entanglement': 'ఎంటాంగిల్‌మెంట్',
    'Measurement': 'కొలత',
    'Vector': 'వెక్టర్',
    'Vectors': 'వెక్టర్లు',
    'Matrix': 'మాత్రిక',
    'Matrices': 'మాత్రికలు',
    'Linear Algebra': 'లీనియర్ ఆల్జీబ్రా',
    'Complex Numbers': 'సంకీర్ణ సంఖ్యలు',
    'Error Correction': 'ఎర్రర్ కరెక్షన్',
    'Simulation': 'సిమ్యులేషన్',
    'Physics': 'భౌతికశాస్త్రం',
    'Hardware': 'హార్డ్‌వేర్',
    'Mechanics': 'మెకానిక్స్',
    'Phase': 'దశ',
    'States': 'స్థితులు',
    'State': 'స్థితి',
    'Transform': 'రూపాంతరం',
    'Fourier': 'ఫోరియర్',
    'Circuits': 'సర్క్యూట్లు',
    'Circuit': 'సర్క్యూట్',
    'Introduction': 'పరిచయం',
    'Foundations': 'పునాదులు',
    'Overview': 'అవలోకనం',
    'Summary': 'సారాంశం'
  },
  kn: {
    'Quantum': 'ಕ್ವಾಂಟಮ್',
    'Computing': 'ಕಂಪ್ಯೂಟಿಂಗ್',
    'Algorithm': 'ಅಲ್ಗಾರಿದಮ್',
    'Algorithms': 'ಅಲ್ಗಾರಿದಮ್‌ಗಳು',
    'Gate': 'ಗೇಟ್',
    'Gates': 'ಗೇಟ್‌ಗಳು',
    'Qubit': 'ಕ್ಯೂಬಿಟ್',
    'Qubits': 'ಕ್ಯೂಬಿಟ್‌ಗಳು',
    'Superposition': 'ಸೂಪರ್‌ಪೊಸಿಷನ್',
    'Entanglement': 'ಎಂಟ್ಯಾಂಗಲ್‌ಮೆಂಟ್',
    'Measurement': 'ಮಾಪನ',
    'Vector': 'ವೆಕ್ಟರ್',
    'Vectors': 'ವೆಕ್ಟರ್‌ಗಳು',
    'Matrix': 'ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    'Matrices': 'ಮ್ಯಾಟ್ರಿಕ್ಸ್‌ಗಳು',
    'Linear Algebra': 'ರೇಖೀಯ ಬೀಜಗಣಿತ',
    'Complex Numbers': 'ಸಂಕೀರ್ಣ ಸಂಖ್ಯೆಗಳು',
    'Error Correction': 'ದೋಷ ತಿದ್ದುಪಡಿ',
    'Simulation': 'ಸಿಮ್ಯುಲೇಶನ್',
    'Physics': 'ಭೌತಶಾಸ್ತ್ರ',
    'Hardware': 'ಹಾರ್ಡ್‌ವೇರ್',
    'Mechanics': 'ಯಂತ್ರಶಾಸ್ತ್ರ',
    'Phase': 'ಹಂತ',
    'States': 'ಸ್ಥಿತಿಗಳು',
    'State': 'ಸ್ಥಿತಿ',
    'Transform': 'ಪರಿವರ್ತನೆ',
    'Fourier': 'ಫೋರಿಯರ್',
    'Circuits': 'ಸರ್ಕ್ಯೂಟ್‌ಗಳು',
    'Circuit': 'ಸರ್ಕ್ಯೂಟ್',
    'Introduction': 'ಪರಿಚಯ',
    'Foundations': 'ಅಡಿಪಾಯ',
    'Overview': 'ಅವಲೋಕನ',
    'Summary': 'ಸಾರಾಂಶ'
  },
  ml: {
    'Quantum': 'ക്വാണ്ടം',
    'Computing': 'കമ്പ്യൂട്ടിംഗ്',
    'Algorithm': 'അൽഗോരിതം',
    'Algorithms': 'അൽഗോരിതങ്ങൾ',
    'Gate': 'ഗേറ്റ്',
    'Gates': 'ഗേറ്റുകൾ',
    'Qubit': 'ക്യുബിറ്റ്',
    'Qubits': 'ക്യുബിറ്റുകൾ',
    'Superposition': 'സൂപ്പർപോസിഷൻ',
    'Entanglement': 'എൻടാംഗിൾമെന്റ്',
    'Measurement': 'അളക്കൽ',
    'Vector': 'വെക്ടർ',
    'Vectors': 'വെക്ടറുകൾ',
    'Matrix': 'മാട്രിക്സ്',
    'Matrices': 'മാട്രിക്സുകൾ',
    'Linear Algebra': 'ലീനിയർ ആൾജിബ്ര',
    'Complex Numbers': 'സങ്കീർണ്ണ സംഖ്യകൾ',
    'Error Correction': 'പിശക് തിരുത്തൽ',
    'Simulation': 'സിമുലേഷൻ',
    'Physics': 'ഭൗതികശാസ്ത്രം',
    'Hardware': 'ഹാർഡ്‌വെയർ',
    'Mechanics': 'മെക്കാനിക്സ്',
    'Phase': 'ഫേസ്',
    'States': 'അവസ്ഥകൾ',
    'State': 'അവസ്ഥ',
    'Transform': 'ട്രാൻസ്ഫോം',
    'Fourier': 'ഫോറിയർ',
    'Circuits': 'സർക്യൂട്ടുകൾ',
    'Circuit': 'സർക്യൂട്ട്',
    'Introduction': 'ആമുഖം',
    'Foundations': 'അടിസ്ഥാനങ്ങൾ',
    'Overview': 'അവലോകനം',
    'Summary': 'സംഗ്രഹം'
  },
  bn: {
    'Quantum': 'কোয়ান্টাম',
    'Computing': 'কম্পিউটিং',
    'Algorithm': 'অ্যালগরিদম',
    'Algorithms': 'অ্যালগরিদম',
    'Gate': 'গেট',
    'Gates': 'গেট',
    'Qubit': 'কিউবিট',
    'Qubits': 'কিউবিট',
    'Superposition': 'সুপারপজিশন',
    'Entanglement': 'এনট্যাঙ্গলমেন্ট',
    'Measurement': 'পরিমাপ',
    'Vector': 'ভেক্টর',
    'Vectors': 'ভেক্টর',
    'Matrix': 'ম্যাট্রিক্স',
    'Matrices': 'ম্যাট্রিক্স',
    'Linear Algebra': 'রৈখিক বীজগণিত',
    'Complex Numbers': 'জটিল সংখ্যা',
    'Error Correction': 'ত্রুটি সংশোধন',
    'Simulation': 'সিমুলেশন',
    'Physics': 'পদার্থবিজ্ঞান',
    'Hardware': 'হার্ডওয়্যার',
    'Mechanics': 'বলবিদ্যা',
    'Phase': 'দশা',
    'States': 'অবস্থা',
    'State': 'অবস্থা',
    'Transform': 'রূপান্তর',
    'Fourier': 'ফুরিয়ার',
    'Circuits': 'সার্কিট',
    'Circuit': 'সার্কিট',
    'Introduction': 'ভূমিকা',
    'Foundations': 'ভিত্তি',
    'Overview': 'সংক্ষিপ্ত বিবরণ',
    'Summary': 'সারসংক্ষেপ'
  },
  mr: {
    'Quantum': 'क्वांटम',
    'Computing': 'कॉम्प्युटिंग',
    'Algorithm': 'अल्गोरिदम',
    'Algorithms': 'अल्गोरिदम',
    'Gate': 'गेट',
    'Gates': 'गेट्स',
    'Qubit': 'क्यूबिट',
    'Qubits': 'क्यूबिट्स',
    'Superposition': 'सुपरपोझिशन',
    'Entanglement': 'एंटँगलमेंट',
    'Measurement': 'मापन',
    'Vector': 'व्हेक्टर',
    'Vectors': 'व्हेक्टर',
    'Matrix': 'मॅट्रिक्स',
    'Matrices': 'मॅट्रिक्स',
    'Linear Algebra': 'रेषीय बीजगणित',
    'Complex Numbers': 'मिश्र संख्या',
    'Error Correction': 'त्रुटी निवारण',
    'Simulation': 'सिम्युलेशन',
    'Physics': 'भौतिकशास्त्र',
    'Hardware': 'हार्डवेअर',
    'Mechanics': 'यांत्रिकी',
    'Phase': 'फेज',
    'States': 'अवस्था',
    'State': 'अवस्था',
    'Transform': 'ट्रान्सफॉर्म',
    'Fourier': 'फूरियर',
    'Circuits': 'सर्किट्स',
    'Circuit': 'सर्किट',
    'Introduction': 'ओळख',
    'Foundations': 'पायाभूत तत्त्वे',
    'Overview': 'विहंगावलोकन',
    'Summary': 'सारांश'
  },
  gu: {
    'Quantum': 'ક્વોન્ટમ',
    'Computing': 'કમ્પ્યુટિંગ',
    'Algorithm': 'અલ્ગોરિધમ',
    'Algorithms': 'અલ્ગોરિધમ્સ',
    'Gate': 'ગેટ',
    'Gates': 'ગેટ્સ',
    'Qubit': 'ક્યુબિટ',
    'Qubits': 'ક્યુબિટ્સ',
    'Superposition': 'સુપરપોઝિશન',
    'Entanglement': 'એન્ટેંગલમેન્ટ',
    'Measurement': 'માપન',
    'Vector': 'વેક્ટર',
    'Vectors': 'વેક્ટર્સ',
    'Matrix': 'મેટ્રિક્સ',
    'Matrices': 'મેટ્રિસિસ',
    'Linear Algebra': 'રેખીય બીજગણિત',
    'Complex Numbers': 'સંકર સંખ્યાઓ',
    'Error Correction': 'ભૂલ સુધારણા',
    'Simulation': 'સિમ્યુલેશન',
    'Physics': 'ભૌતિકશાસ્ત્ર',
    'Hardware': 'હાર્ડવેર',
    'Mechanics': 'મિકેનિક્સ',
    'Phase': 'ફેઝ',
    'States': 'સ્થિતિઓ',
    'State': 'સ્થિતિ',
    'Transform': 'ટ્રાન્સફોર્મ',
    'Fourier': 'ફ્યુરિયર',
    'Circuits': 'સર્કિટ્સ',
    'Circuit': 'સર્કિટ',
    'Introduction': 'પરિચય',
    'Foundations': 'પાયો',
    'Overview': 'ઝાંખી',
    'Summary': 'સારાંશ'
  },
  pa: {
    'Quantum': 'ਕੁਆਂਟਮ',
    'Computing': 'ਕੰਪਿਊਟਿੰਗ',
    'Algorithm': 'ਐਲਗੋਰਿਦਮ',
    'Algorithms': 'ਐਲਗੋਰਿਦਮ',
    'Gate': 'ਗੇਟ',
    'Gates': 'ਗੇਟਸ',
    'Qubit': 'ਕਿਊਬਿਟ',
    'Qubits': 'ਕਿਊਬਿਟਸ',
    'Superposition': 'ਸੁਪਰਪੋਜ਼ੀਸ਼ਨ',
    'Entanglement': 'ਐਨਟੈਂਗਲਮੈਂਟ',
    'Measurement': 'ਮਾਪ',
    'Vector': 'ਵੈਕਟਰ',
    'Vectors': 'ਵੈਕਟਰ',
    'Matrix': 'ਮੈਟ੍ਰਿਕਸ',
    'Matrices': 'ਮੈਟ੍ਰਿਕਸ',
    'Linear Algebra': 'ਰੇਖਿਕ ਬੀਜਗਣਿਤ',
    'Complex Numbers': 'ਕੰਪਲੈਕਸ ਨੰਬਰ',
    'Error Correction': 'ਗਲਤੀ ਸੁਧਾਰ',
    'Simulation': 'ਸਿਮੂਲੇਸ਼ਨ',
    'Physics': 'ਭੌਤਿਕ ਵਿਗਿਆਨ',
    'Hardware': 'ਹਾਰਡਵੇਅਰ',
    'Mechanics': 'ਮਕੈਨਿਕਸ',
    'Phase': 'ਫੇਜ਼',
    'States': 'ਅਵਸਥਾਵਾਂ',
    'State': 'ਅਵਸਥਾ',
    'Transform': 'ਟ੍ਰਾਂਸਫਾਰਮ',
    'Fourier': 'ਫੂਰੀਅਰ',
    'Circuits': 'ਸਰਕਟ',
    'Circuit': 'ਸਰਕਟ',
    'Introduction': 'ਜਾਣ-ਪਛਾਣ',
    'Foundations': 'ਬੁਨਿਆਦ',
    'Overview': 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    'Summary': 'ਸਾਰ'
  }
};

function translateText(text, lang) {
  if (!text || lang === 'en') return text;
  const dict = TERMS[lang];
  if (!dict) return text;
  
  let translated = text;
  // Replace multi-word terms first, then single words
  const keys = Object.keys(dict).sort((a, b) => b.length - a.length);
  for (const k of keys) {
    const reg = new RegExp(`\\b${k}\\b`, 'gi');
    translated = translated.replace(reg, dict[k]);
  }
  return translated;
}

const metadata = {};
lessons.forEach(l => {
  metadata[l.id] = {};
  ['hi', 'ta', 'te', 'kn', 'ml', 'bn', 'mr', 'gu', 'pa'].forEach(lang => {
    metadata[l.id][lang] = {
      title: translateText(l.title, lang),
      summary: translateText(l.summary || l.title, lang)
    };
  });
});

const outContent = `// all_lessons_meta.js
// Comprehensive localized metadata (titles and summaries) for all 209 curriculum lessons across 10 languages
// Generated by build_lesson_meta.js

export const ALL_LESSONS_METADATA = ${JSON.stringify(metadata, null, 2)};
`;

fs.writeFileSync(
  path.join(__dirname, '../src/learning/i18n/content/lessons/all_lessons_meta.js'),
  outContent,
  'utf8'
);
console.log('Successfully generated all_lessons_meta.js for 209 lessons across 10 languages!');
